export const industries = [
  {
    id: 'manufacturing',
    icon: 'Factory',
    title: 'Manufacturing',
    description: 'Websites and software solutions designed for manufacturers — showcasing products, managing inventory, and streamlining operations.',
    useCases: ['Product catalog websites', 'Dealer and distributor portals', 'Inventory tracking systems', 'Order management tools'],
  },
  {
    id: 'industrial',
    icon: 'Wrench',
    title: 'Industrial Organizations',
    description: 'Structured websites and business tools for engineering firms, construction companies, and industrial service providers.',
    useCases: ['Corporate multi-page websites', 'Project showcase portfolios', 'RFQ and inquiry systems', 'Internal project tracking'],
  },
  {
    id: 'retail',
    icon: 'Store',
    title: 'Retail',
    description: 'Online stores, billing solutions, and inventory management tools designed for retail businesses of all sizes.',
    useCases: ['E-commerce websites', 'POS and billing software', 'Inventory management', 'Customer loyalty programs'],
  },
  {
    id: 'wholesale',
    icon: 'Boxes',
    title: 'Wholesale',
    description: 'Business software and websites for wholesalers and distributors managing large product catalogs and B2B clients.',
    useCases: ['B2B product catalogs', 'Bulk order management', 'Inventory and warehouse tracking', 'Customer account portals'],
  },
  {
    id: 'ecommerce',
    icon: 'ShoppingCart',
    title: 'E-commerce',
    description: 'Feature-rich online stores built for businesses that sell products and services directly to consumers.',
    useCases: ['D2C online stores', 'Multi-vendor marketplaces', 'Product comparison features', 'Payment gateway integration'],
  },
  {
    id: 'professional-services',
    icon: 'Briefcase',
    title: 'Professional Services',
    description: 'Professional websites and lead-generation tools for consultants, agencies, law firms, and service businesses.',
    useCases: ['Service showcase websites', 'Appointment booking systems', 'Lead capture landing pages', 'Client management portals'],
  },
  {
    id: 'education',
    icon: 'GraduationCap',
    title: 'Education',
    description: 'Websites and digital tools for schools, training centers, coaching institutes, and educational organizations.',
    useCases: ['Institutional websites', 'Course catalog systems', 'Student inquiry portals', 'Admission management tools'],
  },
  {
    id: 'healthcare',
    icon: 'HeartPulse',
    title: 'Healthcare',
    description: 'Professional websites and management solutions for clinics, hospitals, labs, and healthcare service providers.',
    useCases: ['Clinic and hospital websites', 'Appointment scheduling systems', 'Patient inquiry forms', 'Service directory pages'],
  },
  {
    id: 'real-estate',
    icon: 'Home',
    title: 'Real Estate',
    description: 'Property listing websites and lead-generation solutions for real estate developers, brokers, and agencies.',
    useCases: ['Property listing websites', 'Virtual tour integration', 'Lead generation landing pages', 'Agent and broker portals'],
  },
  {
    id: 'logistics',
    icon: 'Truck',
    title: 'Logistics',
    description: 'Business websites and operational tools for logistics companies, transport providers, and supply chain businesses.',
    useCases: ['Corporate logistics websites', 'Shipment tracking dashboards', 'Fleet management tools', 'Client booking portals'],
  },
  {
    id: 'startups',
    icon: 'Rocket',
    title: 'Startups',
    description: 'Fast, professional websites and MVPs for startups looking to establish their brand and validate their ideas.',
    useCases: ['Startup landing pages', 'MVP web applications', 'Investor pitch websites', 'Early-stage product sites'],
  },
  {
    id: 'local-businesses',
    icon: 'MapPin',
    title: 'Local Businesses',
    description: 'Simple, effective websites and business tools for local shops, service providers, and community businesses.',
    useCases: ['Local business websites', 'Google Business integration', 'Online menu and catalog pages', 'Contact and inquiry forms'],
  },
]
