export const packages = [
  {
    id: 'starter',
    title: 'Starter Website',
    subtitle: 'For individuals, startups, and small businesses that need a professional online presence.',
    icon: 'Sparkles',
    popular: false,
    features: [
      'Up to 5 professionally designed pages',
      'Mobile-responsive design',
      'Contact form with validation',
      'SEO-friendly structure',
      'Social media integration',
      'WhatsApp chat button',
      'Google Maps integration',
      'Basic analytics setup',
    ],
    idealFor: 'Startups, freelancers, small businesses, and professionals who need a clean, credible website.',
    cta: 'Discuss This Package',
  },
  {
    id: 'business',
    title: 'Business Website',
    subtitle: 'For companies that need a complete multi-page website with structured service and business information.',
    icon: 'Building',
    popular: true,
    features: [
      'Up to 15 professionally designed pages',
      'Custom design matching your brand identity',
      'Service and product showcase sections',
      'Lead-generation forms and CTAs',
      'Blog or news section ready',
      'SEO optimization for search visibility',
      'Performance-optimized loading',
      'Content management system',
      'Social media and WhatsApp integration',
      'Post-launch support period',
    ],
    idealFor: 'Growing businesses, agencies, service providers, and companies with multiple offerings.',
    cta: 'Discuss This Package',
  },
  {
    id: 'ecommerce',
    title: 'E-commerce Website',
    subtitle: 'For businesses that want to sell products or services online with a complete store experience.',
    icon: 'ShoppingCart',
    popular: false,
    features: [
      'Full online store with product catalog',
      'Category and filter navigation',
      'Secure checkout and payment integration',
      'Order management dashboard',
      'Customer account system',
      'Inventory tracking integration',
      'Coupon and discount management',
      'Mobile-optimized shopping experience',
      'Email notification system',
      'Analytics and sales reporting',
    ],
    idealFor: 'Retailers, D2C brands, wholesalers, and businesses ready to sell online.',
    cta: 'Discuss This Package',
  },
  {
    id: 'custom-software',
    title: 'Custom Software Solution',
    subtitle: 'For companies that need billing, inventory, workflow, or other internal business software.',
    icon: 'Cog',
    popular: false,
    features: [
      'Requirements analysis and solution design',
      'Custom application development',
      'Role-based access and user management',
      'Dashboard and reporting modules',
      'Data import and export tools',
      'Offline and online operation modes',
      'Integration with existing business systems',
      'Scalable architecture for growth',
      'Training and onboarding support',
      'Ongoing maintenance and updates',
    ],
    idealFor: 'Businesses with unique operational needs that off-the-shelf software cannot address.',
    cta: 'Request Custom Quote',
  },
]
