export const portfolio = [
  {
    id: 'corporate-website',
    title: 'Corporate Website',
    category: 'Website Development',
    description: 'A structured multi-page corporate website designed for a professional services company.',
    tags: ['Multi-page', 'Corporate', 'Responsive'],
    image: '/portfolio/corporate-website.png',
    isSample: true,
  },
  {
    id: 'industrial-website',
    title: 'Industrial Website',
    category: 'Website Development',
    description: 'A comprehensive website for an industrial manufacturer, showcasing products, capabilities, and certifications.',
    tags: ['Industrial', 'Product Catalog', 'Multi-page'],
    image: '/portfolio/industrial-website.png',
    isSample: true,
  },
  {
    id: 'product-landing-page',
    title: 'Product Landing Page',
    category: 'Landing Pages',
    description: 'A high-conversion landing page designed for a product launch campaign with strong lead-capture forms.',
    tags: ['Landing Page', 'Conversion', 'Lead Generation'],
    image: '/portfolio/product-landing-page.png',
    isSample: true,
  },
  {
    id: 'ecommerce-store',
    title: 'E-commerce Store',
    category: 'E-commerce',
    description: 'A user-friendly online store with product catalog, secure checkout, and order management dashboard.',
    tags: ['E-commerce', 'Online Store', 'Payments'],
    image: '/portfolio/ecommerce-store.png',
    isSample: true,
  },
  {
    id: 'billing-software',
    title: 'Billing Software',
    category: 'Business Software',
    description: 'A practical billing application with GST-compliant invoicing, payment tracking, and sales reports.',
    tags: ['Billing', 'Invoicing', 'Offline'],
    image: '/portfolio/billing-software.png',
    isSample: true,
  },
  {
    id: 'inventory-dashboard',
    title: 'Inventory Dashboard',
    category: 'Business Software',
    description: 'An inventory management dashboard with stock tracking, purchase management, and real-time alerts.',
    tags: ['Inventory', 'Dashboard', 'Analytics'],
    image: '/portfolio/inventory-dashboard.png',
    isSample: true,
  },
]
