export const solutions = [
  {
    id: 'digital-presence',
    icon: 'Globe',
    title: 'Digital Presence Solutions',
    problem: 'Your business lacks a professional online presence, making it harder for potential customers to find and trust you.',
    solution: 'We build professional websites that clearly communicate your brand, services, and value — giving your business the credibility it needs to attract and engage customers online.',
    services: ['Business Website Development', 'Industrial and Corporate Websites'],
  },
  {
    id: 'lead-generation',
    icon: 'Target',
    title: 'Lead Generation Solutions',
    problem: 'Your marketing campaigns do not have focused landing pages, and potential leads slip away without converting.',
    solution: 'We create conversion-focused landing pages and lead-capture systems that turn website visitors into real business inquiries, helping you get more value from every marketing effort.',
    services: ['Landing Page Development', 'Business Website Development'],
  },
  {
    id: 'ecommerce-solutions',
    icon: 'ShoppingBag',
    title: 'E-commerce Solutions',
    problem: 'You want to sell products online but lack a reliable, user-friendly platform to manage products, orders, and payments.',
    solution: 'We develop e-commerce websites that provide a smooth shopping experience for your customers and a powerful management dashboard for your team — from product listing to order fulfillment.',
    services: ['E-commerce Website Development'],
  },
  {
    id: 'billing-invoicing',
    icon: 'Receipt',
    title: 'Billing and Invoicing Solutions',
    problem: 'Manual billing is slow, error-prone, and difficult to track, leading to lost revenue and accounting headaches.',
    solution: 'Our billing software simplifies invoicing, payment tracking, and financial record-keeping — designed for everyday use with or without internet connectivity.',
    services: ['Billing Software'],
  },
  {
    id: 'inventory-stock',
    icon: 'Warehouse',
    title: 'Inventory and Stock Management Solutions',
    problem: 'You struggle to track stock levels, purchases, and product movement across locations, leading to stockouts or excess inventory.',
    solution: 'We build inventory management systems that give you real-time visibility into stock levels, automate reorder alerts, and help you make better purchasing decisions.',
    services: ['Inventory Management Software'],
  },
  {
    id: 'internal-software',
    icon: 'Laptop',
    title: 'Custom Internal Software',
    problem: 'Standard tools do not fit your unique workflows, and your team relies on spreadsheets or manual processes that slow things down.',
    solution: 'We develop custom software applications tailored to your specific business operations — replacing manual processes with organized, efficient digital workflows.',
    services: ['Custom Business Software'],
  },
  {
    id: 'workflow-automation',
    icon: 'Workflow',
    title: 'Business Workflow Automation',
    problem: 'Repetitive tasks and disconnected systems consume valuable time and increase the chance of errors.',
    solution: 'We identify opportunities to automate routine business processes and build software that connects your workflows, reduces manual effort, and improves accuracy.',
    services: ['Custom Business Software'],
  },
]
